server:
  port: 2222
  servlet:
    context-path: /mental_health
spring:
  datasource:
    name: mental_health
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/mental_health
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    filters: stat
    initial-size: 2
    max-idel: 10
    max-active: 20
    min-idle: 1
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    min-evictable-time-millis: 300000
    validation-query: select 'x'
    test-while-idle: true
    test-on-borrow: false
mybatis:
  mapper-locations: classpath:com/zj/mapper/*.xml
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 39.106.39.221:22122


